# Declarations for the RanVar extension type.
#
# This augments the pure Python definitions in ranvar.py and exists so that
# modules generated by ranvar2.compiler can cimport RanVar and reach its methods
# as C calls, which is what keeps a compiled simulation out of the interpreter.
#
# Cython requires every C method of the class to be declared here once the file
# exists, so a new @ccall or @cfunc method in ranvar.py has to be added below as
# well or the build fails.
#
# The buffers are declared contiguous ([::1], not [:]). They are numpy arrays
# allocated whole, so they always are, and saying so lets Cython index them by
# offset rather than loading and multiplying a stride on every single access --
# which also lets the C compiler vectorise the shift loops in _add().
#
# Most of the internal methods are declared final. None of them is overridden
# anywhere, and final keeps them out of the vtable, so the C compiler can inline
# them into _add() instead of making an indirect call it cannot see through.
# _add() itself is deliberately NOT final: ranvar2.compiler's generated modules
# cimport RanVar and call it once per sample, which needs it in the vtable.

cimport cython


cdef class RanVar:
    cdef double[::1] _bins
    cdef double[::1] _cnts
    cdef double[::1] _cumw
    cdef double[::1] _gaps

    cdef double[::1] _buf
    cdef double[::1] _bufw
    cdef double[::1] _tb
    cdef double[::1] _tc
    cdef double[::1] _bnds
    cdef int[::1] _guide

    cdef object bins
    cdef object cnts
    cdef object cumw
    cdef object gaps

    cdef object buf
    cdef object bufw
    cdef object tb
    cdef object tc
    cdef object bnds
    cdef object guide

    cdef int maxBins
    cdef int nActive

    cdef int bufCap
    cdef int nBuf

    cdef double _total
    cdef int _stale
    cdef int _ready
    cdef int _guideReady

    @cython.final
    cdef void _allocate(self)

    @cython.final
    cdef void _sortBuffer(self)
    @cython.final
    cdef void _compress(self, int m)
    @cython.final
    cdef void _flush(self)

    cdef void _add(self, double point, double count)

    @cython.final
    cdef void _fitBuffer(self, double[::1] data)

    @cython.final
    cdef double _lower(self)
    @cython.final
    cdef double _upper(self)
    @cython.final
    cdef double _sumWeights(self)
    @cython.final
    cdef void _interpolationBounds(self, int i, double som,
                                   double *yi, double *yi_n)
    @cython.final
    cdef void _rebuildLadder(self)
    @cython.final
    cdef void _buildGuide(self)

    cpdef double quantile(self, double p)
    cpdef double sample(self)


# Normal draws directly from its own parameters rather than a fitted digest, so
# it only needs its two parameters on top of what RanVar already carries.
cdef class Normal(RanVar):
    cdef double _mean
    cdef double _std

    cpdef double sample(self)
    cpdef double quantile(self, double p)


# NegBinom is parameterized by mean and dispersion (the NB2 form), and caches
# the shape/scale of the Gamma half of its Gamma-Poisson mixture so sample()
# only has to multiply rather than convert on every draw.
cdef class NegBinom(RanVar):
    cdef double _mean
    cdef double _dispersion

    cdef double _shape
    cdef double _scale

    cpdef double sample(self)
    cpdef double quantile(self, double p)


# Constant is degenerate: all of its weight sits on a single point, so it only
# needs that point on top of what RanVar already carries.
cdef class Constant(RanVar):
    cdef double _value

    cpdef double sample(self)
    cpdef double quantile(self, double p)


# RanVarArray only needs _at() declared here: it is the one method
# ranvar2.compiler's generated loops call, so it is the one that has to reach
# RanVar._sample through the vtable rather than through Python attribute
# lookup. Everything else on RanVarArray is a plain method, used only from
# ordinary (uncompiled) Python code.
cdef class RanVarArray:
    cdef list _items

    cpdef RanVar _at(self, int i)
