# Declarations for the RanVar extension type.
#
# This augments the pure Python definitions in ranvar.py and exists so that
# modules generated by ranvar2.compiler can cimport RanVar and reach its methods
# as C calls, which is what keeps a compiled simulation out of the interpreter.
#
# Cython requires every C method of the class to be declared here once the file
# exists, so a new @ccall or @cfunc method in ranvar.py has to be added below as
# well or the build fails.

cdef class RanVar:
    cdef double[:] _bins
    cdef double[:] _cnts
    cdef double[:] _cumw
    cdef double[:] _gaps

    cdef object bins
    cdef object cnts
    cdef object cumw
    cdef object gaps

    cdef int maxBins
    cdef int nActive

    cdef double _total
    cdef int _stale

    cpdef int _findLastLesserOrEqualIndex(self, double point)
    cpdef void _shiftRightAndInsert(self, int idx, double point, double count)
    cdef int _findMinimumDifference(self)
    cpdef void _shiftLeftAndOverride(self, int idx)
    cpdef void _add(self, double point, double count)
    cpdef double _lower(self)
    cpdef double _upper(self)
    cdef double _sumWeights(self)
    cdef _interpolationBounds(self, int i, double som)
    cdef void _rebuildLadder(self)
    cpdef double quantile(self, double p)
    cpdef double sample(self)


# Normal draws directly from its own parameters rather than a fitted digest, so
# it only needs its two parameters on top of what RanVar already carries.
cdef class Normal(RanVar):
    cdef double _mean
    cdef double _std

    cpdef double sample(self)
    cpdef double quantile(self, double p)


# NegBinom is parameterized by mean and dispersion (the NB2 form), and caches
# the shape/scale of the Gamma half of its Gamma-Poisson mixture so sample()
# only has to multiply rather than convert on every draw.
cdef class NegBinom(RanVar):
    cdef double _mean
    cdef double _dispersion

    cdef double _shape
    cdef double _scale

    cpdef double sample(self)
    cpdef double quantile(self, double p)
